[package]
name = "acwebber01/fastcast"
description = "A fork of megamonsta2's fork of Xan The Dragon's FastCastRedux module, with minor changes."
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Xan_TheDragon", "megamonsta2", "acwebber01"]
exclude = []
include = ["src", "src/**", "wally.toml", "default.project.json"]

[dependencies]
Table = "megamonsta2/table@1.0.3"
PartCache = "megamonsta2/partcache@1.0.1"
