[package]
name = "kye/znb"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# -- Architecture & State -- 
knit = "sleitnick/knit@1.7.0"
profileservice = "brittonfischer/profileservice@2.1.5"

# -- Motion & Feeling --
advancedspring = "dervexhero/advancedspring@1.0.0"

# -- Projectiles & Raycasting --
fastcast = "acwebber01/fastcast@1.0.1"
partcache = "megamonsta2/partcache@1.1.3"

# -- Networking --
bridgenet2 = "darkestdev/bridgenet2@1.0.2"