[package]
name = "kye/znb"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.7.0"
profileservice = "brittonfischer/profileservice@2.1.5"
spring = "nyxariko/spring@0.1.1"
simplepath = "jessekroeske/simplepath@2.2.2"
cmdr = "evaera/cmdr@1.12.0"
trove = "sleitnick/trove@0.1.0"
fastcast2 = "weenachuangkud/fastcast2@0.1.2"